org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.configuration-cache=false
minecraft_version=1.21.11
loader_version=0.18.1
fabric_version=0.141.4+1.21.11
mod_version=0.1.0
maven_group=dev.luma
archives_base_name=luma-visuals
org.gradle.java.home=C\:\\Program Files\\Eclipse Adoptium\\jdk-21.0.12.8-hotspot